version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/kiko-backend
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:
  ApplicationStart:
    - location: start-server.sh
      timeout: 300
      runas: ubuntu